In [4]:
import pandas as pd
df = pd.read_csv("resources/csv/songs.csv", sep=';')
df.head()

,Artist,Album,Released,Length,Genre,Music Recording Sales (millions),Claimed Sales(millions),Released.1,Soundtrack,Rating
0,Micheal Jackson,Thriller,1982,0:42:19,"pop, rock, R&B",46.0,65,30-Nov-82,NaN,10.0
1,AC/DC,Back in Black,1980,0:42:11,hard rock,26.1,50,25-Jul-80,NaN,9.5
2,Pink Floyd,The Dark Side of the Moon,1973,0:42:49,progressive rock,24.2,45,1-Mar-73,NaN,9.0
3,Whitney Houston,The Bodyguard,1992,0:57:44,"R&B, soul, pop",27.4,44,17-Nov-92,Y,8.5
4,Meaf Loaf,Bat Out of Hell,1977,0:43:08,"hard rock, progressive rock",20.6,43,21-Oct-77,NaN,8.0

In [6]:
# Unique value dataframe
unique_df = df['Released'].unique()
unique_df

array([1982, 1980, 1973, 1992, 1977, 1976])

In [ ]:
# Appying inequality operators for filtering
print(df['Released'] > 1979) # return a boolean series
filtered_df = df[df['Released'] > 1979]
filtered_df

0     True
1     True
2    False
3     True
4    False
5    False
6    False
7    False
Name: Released, dtype: bool

,Artist,Album,Released,Length,Genre,Music Recording Sales (millions),Claimed Sales(millions),Released.1,Soundtrack,Rating
0,Micheal Jackson,Thriller,1982,0:42:19,"pop, rock, R&B",46.0,65,30-Nov-82,NaN,10.0
1,AC/DC,Back in Black,1980,0:42:11,hard rock,26.1,50,25-Jul-80,NaN,9.5
3,Whitney Houston,The Bodyguard,1992,0:57:44,"R&B, soul, pop",27.4,44,17-Nov-92,Y,8.5

In [10]:
# save to csv
filtered_df.to_csv("resources/csv/filtered_songs.csv")